In [38]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import statistics 
import io

In [2]:
source= requests.get('https://fbref.com/en/comps/Big5/shooting/players/Big-5-European-Leagues-Stats').text
soup=BeautifulSoup(source)
table=soup.find_all('table')

In [5]:
ta = table[0]
html_string = str(ta)
df = pd.read_html(io.StringIO(html_string))[0]

In [6]:
df

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4  Keyliane Abdallah             fr FRA
4                     5   Yunis Abdelhamid             ma MAR
...                 ...                ...                ...
2961               2849    Martin Ødegaard             no NOR
2962               2850        Milan Đurić             ba BIH
2963                 Rk             Player             Nation
2964               2851        Milan Đurić             ba BIH
2965               2852   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    FW          Marseille          fr Ligue 1
4                    DF              Reims          fr Ligue 1
...                 ...                ...                 ...
2961                 MF            Arsenal  eng Premier League
2962                 FW      Hellas Verona          it Serie A
2963                Pos              Squad                Comp
2964                 FW              Monza          it Serie A
2965                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Standard  ...  \
                    Age               Born                90s      Gls  ...
0                    23               2000               13.7        0  ...
1                    22               2000               14.1        2  ...
2                    19               2003                1.1        0  ...
3                    17               2006                0.0        0  ...
4                    35               1987               30.9        4  ...
...                 ...                ...                ...      ...  ...
2961                 24               1998               34.3        8  ...
2962                 33               1990               13.4        5  ...
2963                Age               Born                90s      Gls  ...
2964                 33               1990               14.0        4  ...
2965                 20               2003               12.7        0  ...

                          Expected                                \
      Dist  FK  PK  PKatt       xG  npxG  npxG/Sh  G-xG  np:G-xG
0     23.9   0   0      0      0.0   0.0     0.02   0.0      0.0
1     18.4   0   0      0      2.0   2.0     0.11   0.0      0.0
2     15.1   0   0      0      0.1   0.1     0.06  -0.1     -0.1
3      NaN   0   0      0      0.0   0.0      NaN   0.0      0.0
4     15.0   0   1      1      3.4   2.6     0.13  +0.6     +0.4
...    ...  ..  ..    ...      ...   ...      ...   ...      ...
2961  20.2   4   2      2      7.4   5.8     0.08  +0.6     +0.2
2962  12.5   0   1      3      4.5   2.2     0.10  +0.5     +1.8
2963  Dist  FK  PK  PKatt       xG  npxG  npxG/Sh  G-xG  np:G-xG
2964  10.7   0   0      0      3.0   3.0     0.11  +1.0     +1.0
2965  20.5   0   0      0      0.2   0.2     0.03  -0.2     -0.2

     Unnamed: 26_level_0
                 Matches
0                Matches
1                Matches
2                Matches
3                Matches
4                Matches
...                  ...
2961             Matches
2962             Matches
2963             Matches
2964             Matches
2965             Matches

[2966 rows x 27 columns]

In [7]:
df.to_csv('Shooting.csv')

In [8]:
df = pd.read_csv('Shooting.csv', skiprows=0)

In [9]:
df

,Unnamed: 0,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,...,Standard.8,Standard.9,Standard.10,Standard.11,Expected,Expected.1,Expected.2,Expected.3,Expected.4,Unnamed: 26_level_0
0,NaN,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
1,0.0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,...,23.9,0,0,0,0.0,0.0,0.02,0.0,0.0,Matches
2,1.0,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,...,18.4,0,0,0,2.0,2.0,0.11,0.0,0.0,Matches
3,2.0,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,...,15.1,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
4,3.0,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2962,2961.0,2849,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,24,1998,34.3,...,20.2,4,2,2,7.4,5.8,0.08,+0.6,+0.2,Matches
2963,2962.0,2850,Milan Đurić,ba BIH,FW,Hellas Verona,it Serie A,33,1990,13.4,...,12.5,0,1,3,4.5,2.2,0.10,+0.5,+1.8,Matches
2964,2963.0,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
2965,2964.0,2851,Milan Đurić,ba BIH,FW,Monza,it Serie A,33,1990,14.0,...,10.7,0,0,0,3.0,3.0,0.11,+1.0,+1.0,Matches
2966,2965.0,2852,Mateusz Łęgowski,pl POL,MF,Salernitana,it Serie A,20,2003,12.7,...,20.5,0,0,0,0.2,0.2,0.03,-0.2,-0.2,Matches

In [10]:
new_header = df.iloc[0]
df = df[1:]
df.columns = new_header

In [11]:
df

,NaN,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
1,0.0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,...,23.9,0,0,0,0.0,0.0,0.02,0.0,0.0,Matches
2,1.0,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,...,18.4,0,0,0,2.0,2.0,0.11,0.0,0.0,Matches
3,2.0,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,...,15.1,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
4,3.0,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
5,4.0,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,...,15.0,0,1,1,3.4,2.6,0.13,+0.6,+0.4,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2962,2961.0,2849,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,24,1998,34.3,...,20.2,4,2,2,7.4,5.8,0.08,+0.6,+0.2,Matches
2963,2962.0,2850,Milan Đurić,ba BIH,FW,Hellas Verona,it Serie A,33,1990,13.4,...,12.5,0,1,3,4.5,2.2,0.10,+0.5,+1.8,Matches
2964,2963.0,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
2965,2964.0,2851,Milan Đurić,ba BIH,FW,Monza,it Serie A,33,1990,14.0,...,10.7,0,0,0,3.0,3.0,0.11,+1.0,+1.0,Matches
2966,2965.0,2852,Mateusz Łęgowski,pl POL,MF,Salernitana,it Serie A,20,2003,12.7,...,20.5,0,0,0,0.2,0.2,0.03,-0.2,-0.2,Matches

In [12]:
df.to_csv('Shootingg.csv')

In [13]:
df = pd.read_csv('Shootingg.csv')

In [15]:
df.index=df['Rk']
df = df.drop(df.columns[:3], axis=1)

In [16]:
df

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,0,2,...,23.9,0,0,0,0.0,0.0,0.02,0.0,0.0,Matches
2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,2,18,...,18.4,0,0,0,2.0,2.0,0.11,0.0,0.0,Matches
3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,0,2,...,15.1,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,4,21,...,15.0,0,1,1,3.4,2.6,0.13,+0.6,+0.4,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2849,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,24,1998,34.3,8,75,...,20.2,4,2,2,7.4,5.8,0.08,+0.6,+0.2,Matches
2850,Milan Đurić,ba BIH,FW,Hellas Verona,it Serie A,33,1990,13.4,5,22,...,12.5,0,1,3,4.5,2.2,0.10,+0.5,+1.8,Matches
Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Gls,Sh,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
2851,Milan Đurić,ba BIH,FW,Monza,it Serie A,33,1990,14.0,4,26,...,10.7,0,0,0,3.0,3.0,0.11,+1.0,+1.0,Matches
2852,Mateusz Łęgowski,pl POL,MF,Salernitana,it Serie A,20,2003,12.7,0,7,...,20.5,0,0,0,0.2,0.2,0.03,-0.2,-0.2,Matches

In [17]:
df['Nation'] = df['Nation'].str.split(r' ').str.get(1)
df['Comp'] = df['Comp'].str.split(r' ').str.get(1)
df['Comp'] = df['Comp'].str.replace('Premier','Premier League')
df['Comp'] = df['Comp'].str.replace('Ligue','Ligue 1')
df['Comp'] = df['Comp'].str.replace('Serie','Serie A')
df['Comp'] = df['Comp'].str.replace('La','La Liga')

In [18]:
df = df.drop(['Born'],axis=1)
df

,Player,Nation,Pos,Squad,Comp,Age,90s,Gls,Sh,SoT,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,ENG,DF,Bournemouth,Premier League,23,13.7,0,2,0,...,23.9,0,0,0,0.0,0.0,0.02,0.0,0.0,Matches
2,Brenden Aaronson,USA,"MF,FW",Union Berlin,Bundesliga,22,14.1,2,18,7,...,18.4,0,0,0,2.0,2.0,0.11,0.0,0.0,Matches
3,Paxten Aaronson,USA,MF,Eint Frankfurt,Bundesliga,19,1.1,0,2,2,...,15.1,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
4,Keyliane Abdallah,FRA,FW,Marseille,Ligue 1,17,0.0,0,0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
5,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,35,30.9,4,21,7,...,15.0,0,1,1,3.4,2.6,0.13,+0.6,+0.4,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2849,Martin Ødegaard,NOR,MF,Arsenal,Premier League,24,34.3,8,75,21,...,20.2,4,2,2,7.4,5.8,0.08,+0.6,+0.2,Matches
2850,Milan Đurić,BIH,FW,Hellas Verona,Serie A,33,13.4,5,22,13,...,12.5,0,1,3,4.5,2.2,0.10,+0.5,+1.8,Matches
Rk,Player,NaN,Pos,Squad,NaN,Age,90s,Gls,Sh,SoT,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
2851,Milan Đurić,BIH,FW,Monza,Serie A,33,14.0,4,26,6,...,10.7,0,0,0,3.0,3.0,0.11,+1.0,+1.0,Matches
2852,Mateusz Łęgowski,POL,MF,Salernitana,Serie A,20,12.7,0,7,1,...,20.5,0,0,0,0.2,0.2,0.03,-0.2,-0.2,Matches

In [19]:
df = df.drop(df[df['Player'] == 'Player'].index)

In [48]:
df2 = df.copy()

In [49]:
df2

,Player,Nation,Pos,Squad,Comp,Age,90s,Gls,Sh,SoT,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,ENG,DF,Bournemouth,Premier League,23,13.7,0,2,0,...,23.9,0,0,0,0.0,0.0,0.02,0.0,0.0,Matches
2,Brenden Aaronson,USA,"MF,FW",Union Berlin,Bundesliga,22,14.1,2,18,7,...,18.4,0,0,0,2.0,2.0,0.11,0.0,0.0,Matches
3,Paxten Aaronson,USA,MF,Eint Frankfurt,Bundesliga,19,1.1,0,2,2,...,15.1,0,0,0,0.1,0.1,0.06,-0.1,-0.1,Matches
4,Keyliane Abdallah,FRA,FW,Marseille,Ligue 1,17,0.0,0,0,0,...,NaN,0,0,0,0.0,0.0,NaN,0.0,0.0,Matches
5,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,35,30.9,4,21,7,...,15.0,0,1,1,3.4,2.6,0.13,+0.6,+0.4,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2848,Lovro Zvonarek,CRO,"FW,MF",Bayern Munich,Bundesliga,18,1.8,1,1,1,...,16.8,0,0,0,0.1,0.1,0.07,+0.9,+0.9,Matches
2849,Martin Ødegaard,NOR,MF,Arsenal,Premier League,24,34.3,8,75,21,...,20.2,4,2,2,7.4,5.8,0.08,+0.6,+0.2,Matches
2850,Milan Đurić,BIH,FW,Hellas Verona,Serie A,33,13.4,5,22,13,...,12.5,0,1,3,4.5,2.2,0.10,+0.5,+1.8,Matches
2851,Milan Đurić,BIH,FW,Monza,Serie A,33,14.0,4,26,6,...,10.7,0,0,0,3.0,3.0,0.11,+1.0,+1.0,Matches
2852,Mateusz Łęgowski,POL,MF,Salernitana,Serie A,20,12.7,0,7,1,...,20.5,0,0,0,0.2,0.2,0.03,-0.2,-0.2,Matches

In [50]:
df2.drop(df2.columns[-1],inplace=True,axis=1)

In [51]:
df2.drop(df2.columns[-8:-5],inplace=True,axis=1)

In [52]:
df2.drop(df2.columns[4:8],inplace=True,axis=1)

In [53]:
df2.drop(df2.columns[:4],inplace=True,axis=1)

In [54]:
df2

,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,Dist,xG,npxG,npxG/Sh,G-xG,np:G-xG
Rk,,,,,,,,,,,,,
1,2,0,0.0,0.15,0.00,0.00,NaN,23.9,0.0,0.0,0.02,0.0,0.0
2,18,7,38.9,1.28,0.50,0.11,0.29,18.4,2.0,2.0,0.11,0.0,0.0
3,2,2,100.0,1.78,1.78,0.00,0.00,15.1,0.1,0.1,0.06,-0.1,-0.1
4,0,0,NaN,0.00,0.00,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0
5,21,7,33.3,0.68,0.23,0.14,0.43,15.0,3.4,2.6,0.13,+0.6,+0.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2848,1,1,100.0,0.55,0.55,1.00,1.00,16.8,0.1,0.1,0.07,+0.9,+0.9
2849,75,21,28.0,2.18,0.61,0.08,0.29,20.2,7.4,5.8,0.08,+0.6,+0.2
2850,22,13,59.1,1.64,0.97,0.18,0.31,12.5,4.5,2.2,0.10,+0.5,+1.8
2851,26,6,23.1,1.86,0.43,0.15,0.67,10.7,3.0,3.0,0.11,+1.0,+1.0
2852,7,1,14.3,0.55,0.08,0.00,0.00,20.5,0.2,0.2,0.03,-0.2,-0.2

In [55]:
df2.to_csv('Shooting_stat.csv')