In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import statistics 
import io

In [2]:
source= requests.get('https://fbref.com/en/comps/Big5/passing/players/Big-5-European-Leagues-Stats').text
soup=BeautifulSoup(source)
table=soup.find_all('table')

In [3]:
ta = table[0]
html_string = str(ta)
df = pd.read_html(io.StringIO(html_string))[0]

In [4]:
df

     Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                     Rk             Player             Nation
0                     1         Max Aarons            eng ENG
1                     2   Brenden Aaronson             us USA
2                     3    Paxten Aaronson             us USA
3                     4  Keyliane Abdallah             fr FRA
4                     5   Yunis Abdelhamid             ma MAR
...                 ...                ...                ...
2961               2849    Martin Ødegaard             no NOR
2962               2850        Milan Đurić             ba BIH
2963                 Rk             Player             Nation
2964               2851        Milan Đurić             ba BIH
2965               2852   Mateusz Łęgowski             pl POL

     Unnamed: 3_level_0 Unnamed: 4_level_0  Unnamed: 5_level_0  \
                    Pos              Squad                Comp
0                    DF        Bournemouth  eng Premier League
1                 MF,FW       Union Berlin       de Bundesliga
2                    MF     Eint Frankfurt       de Bundesliga
3                    FW          Marseille          fr Ligue 1
4                    DF              Reims          fr Ligue 1
...                 ...                ...                 ...
2961                 MF            Arsenal  eng Premier League
2962                 FW      Hellas Verona          it Serie A
2963                Pos              Squad                Comp
2964                 FW              Monza          it Serie A
2965                 MF        Salernitana          it Serie A

     Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0 Total  ...  \
                    Age               Born                90s   Cmp  ...
0                    23               2000               13.7   450  ...
1                    22               2000               14.1   365  ...
2                    19               2003                1.1    41  ...
3                    17               2006                0.0     1  ...
4                    35               1987               30.9  1552  ...
...                 ...                ...                ...   ...  ...
2961                 24               1998               34.3  1692  ...
2962                 33               1990               13.4   181  ...
2963                Age               Born                90s   Cmp  ...
2964                 33               1990               14.0   140  ...
2965                 20               2003               12.7   292  ...

     Unnamed: 23_level_0 Unnamed: 24_level_0 Expected         \
                     Ast                 xAG       xA  A-xAG
0                      1                 0.8      0.9   +0.2
1                      2                 1.9      2.0   +0.1
2                      1                 0.1      0.1   +0.9
3                      0                 0.0      0.0    0.0
4                      0                 0.3      0.6   -0.3
...                  ...                 ...      ...    ...
2961                  10                 9.6     11.2   +0.4
2962                   1                 1.2      0.5   -0.2
2963                 Ast                 xAG       xA  A-xAG
2964                   1                 0.7      0.2   +0.3
2965                   0                 0.2      0.4   -0.2

     Unnamed: 27_level_0 Unnamed: 28_level_0 Unnamed: 29_level_0  \
                      KP                 1/3                 PPA
0                      7                  25                  13
1                     22                  30                  14
2                      1                   4                   2
3                      0                   0                   0
4                      8                 129                   3
...                  ...                 ...                 ...
2961                 102                 160                 130
2962                  16                  18                   3
2963                  KP                 1/3                 PPA
2964                   5                   3                   2
2965                   7                  30                   5

     Unnamed: 30_level_0 Unnamed: 31_level_0 Unnamed: 32_level_0
                   CrsPA                PrgP             Matches
0                      2                  43             Matches
1                      3                  56             Matches
2                      0                   5             Matches
3                      0                   0             Matches
4                      0                 137             Matches
...                  ...                 ...                 ...
2961                  13                 344             Matches
2962                   0                  15             Matches
2963               CrsPA                PrgP             Matches
2964                   0                   8             Matches
2965                   1                  37             Matches

[2966 rows x 33 columns]

In [5]:
df.to_csv('Passing.csv')

In [6]:
df = pd.read_csv('Passing.csv', skiprows=0)

In [7]:
df

,Unnamed: 0,Unnamed: 0_level_0,Unnamed: 1_level_0,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0,...,Unnamed: 23_level_0,Unnamed: 24_level_0,Expected,Expected.1,Unnamed: 27_level_0,Unnamed: 28_level_0,Unnamed: 29_level_0,Unnamed: 30_level_0,Unnamed: 31_level_0,Unnamed: 32_level_0
0,NaN,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
1,0.0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,...,1,0.8,0.9,+0.2,7,25,13,2,43,Matches
2,1.0,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,...,2,1.9,2.0,+0.1,22,30,14,3,56,Matches
3,2.0,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,...,1,0.1,0.1,+0.9,1,4,2,0,5,Matches
4,3.0,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,...,0,0.0,0.0,0.0,0,0,0,0,0,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2962,2961.0,2849,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,24,1998,34.3,...,10,9.6,11.2,+0.4,102,160,130,13,344,Matches
2963,2962.0,2850,Milan Đurić,ba BIH,FW,Hellas Verona,it Serie A,33,1990,13.4,...,1,1.2,0.5,-0.2,16,18,3,0,15,Matches
2964,2963.0,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
2965,2964.0,2851,Milan Đurić,ba BIH,FW,Monza,it Serie A,33,1990,14.0,...,1,0.7,0.2,+0.3,5,3,2,0,8,Matches
2966,2965.0,2852,Mateusz Łęgowski,pl POL,MF,Salernitana,it Serie A,20,2003,12.7,...,0,0.2,0.4,-0.2,7,30,5,1,37,Matches

In [8]:
new_header = df.iloc[0]
df = df[1:]
df.columns = new_header

In [9]:
df

,NaN,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
1,0.0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,...,1,0.8,0.9,+0.2,7,25,13,2,43,Matches
2,1.0,2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,...,2,1.9,2.0,+0.1,22,30,14,3,56,Matches
3,2.0,3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,...,1,0.1,0.1,+0.9,1,4,2,0,5,Matches
4,3.0,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,...,0,0.0,0.0,0.0,0,0,0,0,0,Matches
5,4.0,5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,...,0,0.3,0.6,-0.3,8,129,3,0,137,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2962,2961.0,2849,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,24,1998,34.3,...,10,9.6,11.2,+0.4,102,160,130,13,344,Matches
2963,2962.0,2850,Milan Đurić,ba BIH,FW,Hellas Verona,it Serie A,33,1990,13.4,...,1,1.2,0.5,-0.2,16,18,3,0,15,Matches
2964,2963.0,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
2965,2964.0,2851,Milan Đurić,ba BIH,FW,Monza,it Serie A,33,1990,14.0,...,1,0.7,0.2,+0.3,5,3,2,0,8,Matches
2966,2965.0,2852,Mateusz Łęgowski,pl POL,MF,Salernitana,it Serie A,20,2003,12.7,...,0,0.2,0.4,-0.2,7,30,5,1,37,Matches

In [10]:
df.to_csv('Passingg.csv')

In [11]:
df = pd.read_csv('Passingg.csv')

In [12]:
df.index=df['Rk']
df = df.drop(df.columns[:3], axis=1)

In [13]:
df

,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Cmp,Att,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,23,2000,13.7,450,581,...,1,0.8,0.9,+0.2,7,25,13,2,43,Matches
2,Brenden Aaronson,us USA,"MF,FW",Union Berlin,de Bundesliga,22,2000,14.1,365,472,...,2,1.9,2.0,+0.1,22,30,14,3,56,Matches
3,Paxten Aaronson,us USA,MF,Eint Frankfurt,de Bundesliga,19,2003,1.1,41,50,...,1,0.1,0.1,+0.9,1,4,2,0,5,Matches
4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,17,2006,0.0,1,1,...,0,0.0,0.0,0.0,0,0,0,0,0,Matches
5,Yunis Abdelhamid,ma MAR,DF,Reims,fr Ligue 1,35,1987,30.9,1552,1836,...,0,0.3,0.6,-0.3,8,129,3,0,137,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2849,Martin Ødegaard,no NOR,MF,Arsenal,eng Premier League,24,1998,34.3,1692,2006,...,10,9.6,11.2,+0.4,102,160,130,13,344,Matches
2850,Milan Đurić,ba BIH,FW,Hellas Verona,it Serie A,33,1990,13.4,181,334,...,1,1.2,0.5,-0.2,16,18,3,0,15,Matches
Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Cmp,Att,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
2851,Milan Đurić,ba BIH,FW,Monza,it Serie A,33,1990,14.0,140,272,...,1,0.7,0.2,+0.3,5,3,2,0,8,Matches
2852,Mateusz Łęgowski,pl POL,MF,Salernitana,it Serie A,20,2003,12.7,292,378,...,0,0.2,0.4,-0.2,7,30,5,1,37,Matches

In [14]:
df['Nation'] = df['Nation'].str.split(r' ').str.get(1)
df['Comp'] = df['Comp'].str.split(r' ').str.get(1)
df['Comp'] = df['Comp'].str.replace('Premier','Premier League')
df['Comp'] = df['Comp'].str.replace('Ligue','Ligue 1')
df['Comp'] = df['Comp'].str.replace('Serie','Serie A')
df['Comp'] = df['Comp'].str.replace('La','La Liga')

In [15]:
df = df.drop(['Born'],axis=1)
df

,Player,Nation,Pos,Squad,Comp,Age,90s,Cmp,Att,Cmp%,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,ENG,DF,Bournemouth,Premier League,23,13.7,450,581,77.5,...,1,0.8,0.9,+0.2,7,25,13,2,43,Matches
2,Brenden Aaronson,USA,"MF,FW",Union Berlin,Bundesliga,22,14.1,365,472,77.3,...,2,1.9,2.0,+0.1,22,30,14,3,56,Matches
3,Paxten Aaronson,USA,MF,Eint Frankfurt,Bundesliga,19,1.1,41,50,82.0,...,1,0.1,0.1,+0.9,1,4,2,0,5,Matches
4,Keyliane Abdallah,FRA,FW,Marseille,Ligue 1,17,0.0,1,1,100.0,...,0,0.0,0.0,0.0,0,0,0,0,0,Matches
5,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,35,30.9,1552,1836,84.5,...,0,0.3,0.6,-0.3,8,129,3,0,137,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2849,Martin Ødegaard,NOR,MF,Arsenal,Premier League,24,34.3,1692,2006,84.3,...,10,9.6,11.2,+0.4,102,160,130,13,344,Matches
2850,Milan Đurić,BIH,FW,Hellas Verona,Serie A,33,13.4,181,334,54.2,...,1,1.2,0.5,-0.2,16,18,3,0,15,Matches
Rk,Player,NaN,Pos,Squad,NaN,Age,90s,Cmp,Att,Cmp%,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
2851,Milan Đurić,BIH,FW,Monza,Serie A,33,14.0,140,272,51.5,...,1,0.7,0.2,+0.3,5,3,2,0,8,Matches
2852,Mateusz Łęgowski,POL,MF,Salernitana,Serie A,20,12.7,292,378,77.2,...,0,0.2,0.4,-0.2,7,30,5,1,37,Matches

In [16]:
df = df.drop(df[df['Player'] == 'Player'].index)

In [42]:
df2 = df.copy()

In [35]:
df2

,Player,Nation,Pos,Squad,Comp,Age,90s,Cmp,Att,Cmp%,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,Max Aarons,ENG,DF,Bournemouth,Premier League,23,13.7,450,581,77.5,...,1,0.8,0.9,+0.2,7,25,13,2,43,Matches
2,Brenden Aaronson,USA,"MF,FW",Union Berlin,Bundesliga,22,14.1,365,472,77.3,...,2,1.9,2.0,+0.1,22,30,14,3,56,Matches
3,Paxten Aaronson,USA,MF,Eint Frankfurt,Bundesliga,19,1.1,41,50,82.0,...,1,0.1,0.1,+0.9,1,4,2,0,5,Matches
4,Keyliane Abdallah,FRA,FW,Marseille,Ligue 1,17,0.0,1,1,100.0,...,0,0.0,0.0,0.0,0,0,0,0,0,Matches
5,Yunis Abdelhamid,MAR,DF,Reims,Ligue 1,35,30.9,1552,1836,84.5,...,0,0.3,0.6,-0.3,8,129,3,0,137,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2848,Lovro Zvonarek,CRO,"FW,MF",Bayern Munich,Bundesliga,18,1.8,50,60,83.3,...,0,0.2,0.3,-0.2,2,5,1,0,7,Matches
2849,Martin Ødegaard,NOR,MF,Arsenal,Premier League,24,34.3,1692,2006,84.3,...,10,9.6,11.2,+0.4,102,160,130,13,344,Matches
2850,Milan Đurić,BIH,FW,Hellas Verona,Serie A,33,13.4,181,334,54.2,...,1,1.2,0.5,-0.2,16,18,3,0,15,Matches
2851,Milan Đurić,BIH,FW,Monza,Serie A,33,14.0,140,272,51.5,...,1,0.7,0.2,+0.3,5,3,2,0,8,Matches
2852,Mateusz Łęgowski,POL,MF,Salernitana,Serie A,20,12.7,292,378,77.2,...,0,0.2,0.4,-0.2,7,30,5,1,37,Matches

In [43]:
df2.drop(df2.columns[-1],inplace=True,axis=1)

In [44]:
df2.drop(df2.columns[:6],inplace=True,axis=1)

In [37]:
df2

,Cmp,Att,Cmp%,TotDist,PrgDist,Cmp.1,Att.1,Cmp%.1,Cmp.2,Att.2,...,Ast,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP,Matches
Rk,,,,,,,,,,,,,,,,,,,,,
1,450,581,77.5,7402,2789,220,248,88.7,188,235,...,1,0.8,0.9,+0.2,7,25,13,2,43,Matches
2,365,472,77.3,4890,1506,206,240,85.8,105,130,...,2,1.9,2.0,+0.1,22,30,14,3,56,Matches
3,41,50,82.0,576,71,20,25,80.0,20,22,...,1,0.1,0.1,+0.9,1,4,2,0,5,Matches
4,1,1,100.0,8,0,1,1,100.0,0,0,...,0,0.0,0.0,0.0,0,0,0,0,0,Matches
5,1552,1836,84.5,29618,9672,487,548,88.9,893,976,...,0,0.3,0.6,-0.3,8,129,3,0,137,Matches
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2848,50,60,83.3,766,123,20,23,87.0,25,29,...,0,0.2,0.3,-0.2,2,5,1,0,7,Matches
2849,1692,2006,84.3,25780,7898,907,992,91.4,635,744,...,10,9.6,11.2,+0.4,102,160,130,13,344,Matches
2850,181,334,54.2,2116,392,130,213,61.0,32,69,...,1,1.2,0.5,-0.2,16,18,3,0,15,Matches
2851,140,272,51.5,1700,251,93,156,59.6,35,86,...,1,0.7,0.2,+0.3,5,3,2,0,8,Matches
2852,292,378,77.2,4268,1261,169,196,86.2,95,120,...,0,0.2,0.4,-0.2,7,30,5,1,37,Matches

In [45]:
df2.drop(df2.columns[6:16],inplace=True,axis=1)

In [46]:
df2

,90s,Cmp,Att,Cmp%,TotDist,PrgDist,xAG,xA,A-xAG,KP,1/3,PPA,CrsPA,PrgP
Rk,,,,,,,,,,,,,,
1,13.7,450,581,77.5,7402,2789,0.8,0.9,+0.2,7,25,13,2,43
2,14.1,365,472,77.3,4890,1506,1.9,2.0,+0.1,22,30,14,3,56
3,1.1,41,50,82.0,576,71,0.1,0.1,+0.9,1,4,2,0,5
4,0.0,1,1,100.0,8,0,0.0,0.0,0.0,0,0,0,0,0
5,30.9,1552,1836,84.5,29618,9672,0.3,0.6,-0.3,8,129,3,0,137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2848,1.8,50,60,83.3,766,123,0.2,0.3,-0.2,2,5,1,0,7
2849,34.3,1692,2006,84.3,25780,7898,9.6,11.2,+0.4,102,160,130,13,344
2850,13.4,181,334,54.2,2116,392,1.2,0.5,-0.2,16,18,3,0,15
2851,14.0,140,272,51.5,1700,251,0.7,0.2,+0.3,5,3,2,0,8
2852,12.7,292,378,77.2,4268,1261,0.2,0.4,-0.2,7,30,5,1,37

In [60]:
df3 = df2.copy()
df3 = df3.rename(columns={'Cmp': 'Cmp90','Att': 'Att90','TotDist':'PassTotDist90','PrgDist':'PassPrgDist90','KP':'KP90','1/3':'Pass1/3(90)','PPA':'PPA90','CrsPA':'CrsPA90','PrgP':'PrgP90'})
df3

,90s,Cmp90,Att90,Cmp%,PassTotDist90,PassPrgDist90,xAG,xA,A-xAG,KP90,Pass1/3(90),PPA90,CrsPA90,PrgP90
Rk,,,,,,,,,,,,,,
1,13.7,450,581,77.5,7402,2789,0.8,0.9,+0.2,7,25,13,2,43
2,14.1,365,472,77.3,4890,1506,1.9,2.0,+0.1,22,30,14,3,56
3,1.1,41,50,82.0,576,71,0.1,0.1,+0.9,1,4,2,0,5
4,0.0,1,1,100.0,8,0,0.0,0.0,0.0,0,0,0,0,0
5,30.9,1552,1836,84.5,29618,9672,0.3,0.6,-0.3,8,129,3,0,137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2848,1.8,50,60,83.3,766,123,0.2,0.3,-0.2,2,5,1,0,7
2849,34.3,1692,2006,84.3,25780,7898,9.6,11.2,+0.4,102,160,130,13,344
2850,13.4,181,334,54.2,2116,392,1.2,0.5,-0.2,16,18,3,0,15
2851,14.0,140,272,51.5,1700,251,0.7,0.2,+0.3,5,3,2,0,8
2852,12.7,292,378,77.2,4268,1261,0.2,0.4,-0.2,7,30,5,1,37

In [49]:
df3.dtypes

90s          object
Cmp90        object
Att90        object
Cmp%         object
TotDist90    object
PrgDist90    object
xAG          object
xA           object
A-xAG        object
KP90         object
1/3(90)      object
PPA90        object
CrsPA90      object
PrgP90       object
dtype: object

In [62]:
df3 = df3.astype(float)

In [63]:
df3['Cmp90']=df3['Cmp90']/df3['90s']

In [64]:
df3['Att90']=df3['Att90']/df3['90s']
df3['PassTotDist90']=df3['PassTotDist90']/df3['90s']
df3['PassPrgDist90']=df3['PassPrgDist90']/df3['90s']
df3['KP90']=df3['KP90']/df3['90s']
df3['Pass1/3(90)']=df3['Pass1/3(90)']/df3['90s']
df3['PPA90']=df3['PPA90']/df3['90s']
df3['CrsPA90']=df3['CrsPA90']/df3['90s']
df3['PrgP90']=df3['PrgP90']/df3['90s']

In [65]:
df3 = df3.round(2)

In [66]:
df3.drop(df2.columns[0],inplace=True,axis=1)

In [67]:
df3

,Cmp90,Att90,Cmp%,PassTotDist90,PassPrgDist90,xAG,xA,A-xAG,KP90,Pass1/3(90),PPA90,CrsPA90,PrgP90
Rk,,,,,,,,,,,,,
1,32.85,42.41,77.5,540.29,203.58,0.8,0.9,0.2,0.51,1.82,0.95,0.15,3.14
2,25.89,33.48,77.3,346.81,106.81,1.9,2.0,0.1,1.56,2.13,0.99,0.21,3.97
3,37.27,45.45,82.0,523.64,64.55,0.1,0.1,0.9,0.91,3.64,1.82,0.00,4.55
4,inf,inf,100.0,inf,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
5,50.23,59.42,84.5,958.51,313.01,0.3,0.6,-0.3,0.26,4.17,0.10,0.00,4.43
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2848,27.78,33.33,83.3,425.56,68.33,0.2,0.3,-0.2,1.11,2.78,0.56,0.00,3.89
2849,49.33,58.48,84.3,751.60,230.26,9.6,11.2,0.4,2.97,4.66,3.79,0.38,10.03
2850,13.51,24.93,54.2,157.91,29.25,1.2,0.5,-0.2,1.19,1.34,0.22,0.00,1.12
2851,10.00,19.43,51.5,121.43,17.93,0.7,0.2,0.3,0.36,0.21,0.14,0.00,0.57
2852,22.99,29.76,77.2,336.06,99.29,0.2,0.4,-0.2,0.55,2.36,0.39,0.08,2.91

In [68]:
df3.to_csv('Passing_stat.csv')